config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/aboutus'
  get 'home/index'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to:user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many:friend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new

    @friend=current_user.friend.build

  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend= current_user.friend.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    #@friend=current_user.friend.find(params[id]).build
    
    redirect_to friends_path, notice: "Not Authorize to edit/delete " if @friend.user_id!=current_user.id
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def aboutus
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3" style="padding:3px;width:700px; height:500px; align:center">
  <div>
    <%= form.label :first_name , class:"form-label" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :last_name, class:"form-label",style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :email, class:"form-label", style: "display: block" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div>
    <%= form.label :phone, class:"form-label", style: "display: block" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div>
    <%= form.label :twitter, class:"form-label", style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>

  <div>
    <%= form.number_field:user_id, id: :friend_user_id, value:current_user.id,type: :hidden, class:"form-control" %>
  </div>



  <div >
  <%= form.submit :class => 'btn btn-secondary' %>
</div>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>" >
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<div>
  <%= link_to "Show Friend", @friend,class:'btn btn-secondary' %> 
  <%= link_to "Back", friends_path,class:'btn btn-secondary' %>
 
  <%= button_to "Destroy", @friend, method: :delete, class:'btn btn-danger' %>
  
</div>

app/views/friends/index.html.erb
<%if user_signed_in?%>
<h1>Friends List</h1>
<table class="table">
  <thead class="table-dark">
  <th>Name</th>
  <th>Email</th>
  <th>Phone</th>
  <th>Twitter</th>
  <th>User_Id</th>
  <th>Action</th>
  </thead>
  <tbody>
  
   <div id="friends">
   <% @friends.each do |friend| %>
    
   <% if friend.user==current_user%> 
  <tr>
   <td> 
    <%= link_to friend.first_name+" "+friend.last_name, edit_friend_path(friend) %>
    </td>

    <td> 
    <%=  friend.email %>
    </td>

    <td> 
    <%=  friend.phone %>
    </td>
    <td> 
    <%=  friend.twitter %>
    </td>

    <td> 
    <%=  friend.user_id %>
    </td>

    <td>
      
      <%= button_to "Destroy", friend, method: :delete, class:'btn btn-danger' %>
    </td>
    </tr>
    <%end%>
    <% end %>
    </div>
  </tbody>
</table>
<%= link_to "New friend", new_friend_path %>

<%else%>
<h1>Welcome to Home page!!</h1>
<%end%>

app/views/friends/new.html.erb
<h1>Add a new friend</h1>

<%= render "form", friend: @friend %>

<br>

<div style="--bs-link-opacity: .5">
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:'btn btn-secondary' %> |
  <%= link_to "Back to friends", friends_path %>
  <br>

  <%= button_to "Destroy this friend", @friend, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%=link_to 'Friends App', root_path, class:"navbar-brand" %>
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">

        <%=link_to 'About Us', home_aboutus_path, class:"nav-link active" %>

        </li>


        <li class="nav-item">

        <%=link_to 'Add Friend', new_friend_path, class:"nav-link active" %>

        </li>

        

        

        

        

        <% if user_signed_in? %>
          <li class="nav-item">
          <%=link_to 'Edit Profile', edit_user_registration_path, class:"nav-link active" %>
          </li>

          <li class="nav-item">
          <%=link_to 'SignOut',  destroy_user_session_path , class:"nav-link active" %>
          </li>
          
          

        <% else %>

        <li class="nav-item">
        <%=link_to 'SignIn', new_user_session_path, class:"nav-link active" %>
        </li>

        <li class="nav-item">
          <%=link_to 'SignUP', new_user_registration_path, class:"nav-link active" %>
          </li>

        <%end%>


    
      </ul>
     
    </div>
  </div>
</nav>

app/views/home/aboutus.html.erb
<h1>about us page!!</h1>

app/views/home/index.html.erb
<h1>Hello World!!</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-secondary" role="alert">
<%= notice%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    </head>
  <body>
  
  <%= render 'home/header'%>
  
  <div class='container'>
  <% if notice%>
  <br/>
      <%= render 'layouts/alerts' %>
  <% end %>

  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

    <%= yield %>

</div>
    </body>
</html>